# Generated by Django 4.2.7 on 2024-02-16 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзини', 'verbose_name_plural': 'Корзини'},
        ),
    ]
