# Generated by Django 4.2.7 on 2024-02-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='requires_delivery',
        ),
        migrations.AddField(
            model_name='order',
            name='requires_delivery_1',
            field=models.BooleanField(default=False, verbose_name='Нова пошта'),
        ),
        migrations.AddField(
            model_name='order',
            name='requires_delivery_2',
            field=models.BooleanField(default=False, verbose_name='Укр пошта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплата карткою'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_on_get',
            field=models.BooleanField(default=False, verbose_name='Оплата при отриманні'),
        ),
    ]
